# -*- coding: utf-8 -*-
"""DataTransformLab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3xpHcko4oIzngKtEkCRU72qPb7hordI
"""

import pandas as pd

url = 'https://drive.google.com/file/d/1mminKe9fwqpJ59POiveHv_UrRYVSPjjY/edit'
url = 'https://drive.google.com/uc?id=' + url.split('/')[-2]
df = pd.read_csv(url)
df.head()
# print(len(df))

df = df.drop(columns=['EVENT_NO_STOP', 'GPS_SATELLITES', 'GPS_HDOP'])
df.head()

df = pd.read_csv(url, usecols=['EVENT_NO_TRIP', 'OPD_DATE', 'VEHICLE_ID', 'METERS', 'ACT_TIME', 'GPS_LONGITUDE', 'GPS_LATITUDE'])
print(df.head())

def decode_timestamp(row):
    date = pd.to_datetime(row['OPD_DATE'], format='%d%b%Y:%H:%M:%S')
    time = pd.to_timedelta(row['ACT_TIME'], unit='s')
    return date + time

df['TIMESTAMP'] = df.apply(decode_timestamp, axis=1)
df = df.drop(columns=['OPD_DATE', 'ACT_TIME'])
df.head()

df['dMETERS'] = df['METERS'].diff()
df['dTIMESTAMP'] = df['TIMESTAMP'].diff().dt.total_seconds()
df['SPEED'] = df.apply(lambda row: row['dMETERS'] / row['dTIMESTAMP'], axis=1)
df = df.drop(columns=['dMETERS', 'dTIMESTAMP'])
df.head()
print("Minimum:", df['SPEED'].min())
print("Maximum:", df['SPEED'].max())
print("Average:", df['SPEED'].mean())